export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const SINGLE_REVIEW_REQUEST = "SINGLE_REVIEW_REQUEST";
export const SINGLE_REVIEW_SUCCESS = "SINGLE_REVIEW_SUCCESS";
export const SINGLE_REVIEW_FAIL = "SINGLE_REVIEW_FAIL";

export const RECIPE_REVIEWS_REQUEST = "RECIPE_REVIEWS_REQUEST";
export const RECIPE_REVIEWS_SUCCESS = "RECIPE_REVIEWS_SUCCESS";
export const RECIPE_REVIEWS_FAIL = "RECIPE_REVIEWS_FAIL";

export const LIST_USER_REVIEWS_REQUEST = "LIST_USER_REVIEWS_REQUEST";
export const LIST_USER_REVIEWS_SUCCESS = "LIST_USER_REVIEWS_SUCCESS";
export const LIST_USER_REVIEWS_FAIL = "LIST_USER_REVIEWS_FAIL";

export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";
export const REVIEW_CREATE_RESET = "REVIEW_CREATE_RESET";

export const REVIEW_UPDATE_REQUEST = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";
export const REVIEW_UPDATE_RESET = "REVIEW_UPDATE_RESET";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
export const REVIEW_DELETE_RESET = "REVIEW_DELETE_RESET";
