export const UPLOAD_SINGLE_REQUEST = "UPLOAD_SINGLE_REQUEST";
export const UPLOAD_SINGLE_SUCCESS = "UPLOAD_SINGLE_SUCCESS";
export const UPLOAD_SINGLE_FAIL = "UPLOAD_SINGLE_FAIL";

export const UPLOAD_MULTIPLE_REQUEST = "UPLOAD_MULTIPLE_REQUEST";
export const UPLOAD_MULTIPLE_SUCCESS = "UPLOAD_MULTIPLE_SUCCESS";
export const UPLOAD_MULTIPLE_FAIL = "UPLOAD_MULTIPLE_FAIL";
